name: Build & Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Run docker-compose
        run: docker-compose -f kafka-docker-compose.yml up -d

      - name: Verify running containers
        run: docker ps
