name: Docker Image CI

on:
  push:
    branches: [ "git-workflow" ]
  pull_request:
    branches: [ "git-workflow" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker-compose -f kafka-docker-compose.yml up -d
